alerting:
  aws-ses:
    region: "eu-west-2"
    from: "khalfan.k@outlook.com"
    to: "khalfan.k@outlook.com"
    default-alert:
      failure-threshold: 3
      success-threshold: 3
      send-on-resolved: true

endpoints:
  - name: gatus-self
    group: core
    url: https://tm.kkhalfan.com
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"

  - name: aws-health-dashboard
    group: aws-dependencies
    url: "https://health.aws.amazon.com/health/status"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: acm-cert-expiry
    group: core
    url: "https://tm.kkhalfan.com"
    interval: 1h
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 720h"

  - name: dns-resolution
    group: core
    url: "8.8.8.8"
    interval: 5m
    dns:
      query-name: "kkhalfan.com"
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NOERROR"

  - name: github-api
    group: external-demo
    url: "https://api.github.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].current_user_url != null"

  - name: demo-deliberate-failure
    group: core
    url: "https://demo.kkhalfan.com/"
    interval: 10s
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: aws-ses


